Repository ocean-eddy-cpt/gcm-filters, pull requests merged in 2021-05, with the labels that each got.

#67 Tutorial on numerical instability and coarsening
  docs/index.rst
  docs/tutorial.ipynb
  docs/tutorial_numerical_instability.ipynb
Labels: documentation

#66 Add method to plot filter shape
  docs/environment.yml
  docs/tutorial.ipynb
  gcm_filters/filter.py
  requirements.txt
  tests/test_filter.py
Labels: documentation, enhancement

#60 Added how to build docs locally
  docs/how_to_contribute.rst
Labels: documentation

#34 Vector Laplacian on C-grid
  gcm_filters/filter.py
  gcm_filters/kernels.py
  tests/test_filter.py
  tests/test_kernels.py
Labels: kernels
